<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\tModLoader.targets" />
	<PropertyGroup>
	</PropertyGroup>
	

	<ItemGroup>
		<Reference Include="StructureHelper">
			<HintPath>lib\StructureHelper.dll</HintPath>
		</Reference>
		<Reference Include="SubworldLibrary">
			<HintPath>lib\SubworldLibrary.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="tModLoader.CodeAssist" Version="0.1.5" />
	</ItemGroup>

</Project>